# Generated by Django 4.2.9 on 2025-12-29 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategoriya nomi')),
                ('name_uz', models.CharField(blank=True, max_length=100, verbose_name="Nomi (O'zbekcha)")),
                ('name_ru', models.CharField(blank=True, max_length=100, verbose_name='Nomi (Русский)')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Nomi (English)')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Taom nomi')),
                ('name_uz', models.CharField(blank=True, max_length=200, verbose_name="Nomi (O'zbekcha)")),
                ('name_ru', models.CharField(blank=True, max_length=200, verbose_name='Nomi (Русский)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Nomi (English)')),
                ('description', models.TextField(blank=True, verbose_name="Ta'rif")),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Narxi (so'm)")),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_items/', verbose_name='Rasm')),
                ('is_available', models.BooleanField(default=True, verbose_name='Mavjud')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Mashhur')),
                ('preparation_time', models.IntegerField(default=15, verbose_name='Tayyorlash vaqti (daqiqa)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurant.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Menyu elementi',
                'verbose_name_plural': 'Menyu elementlari',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='Stol raqami')),
                ('floor', models.IntegerField(default=1, verbose_name='Etaj')),
                ('seats', models.IntegerField(default=4, verbose_name="O'rindiqlar soni")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR kod')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': 'Stol',
                'verbose_name_plural': 'Stollar',
                'ordering': ['floor', 'number'],
            },
        ),
        migrations.CreateModel(
            name='WaiterAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='Etaj')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tayinlangan vaqt')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='restaurant.table', verbose_name='Stol')),
                ('waiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL, verbose_name='Ofitsant')),
            ],
            options={
                'verbose_name': 'Ofitsant tayinlash',
                'verbose_name_plural': 'Ofitsant tayinlashlar',
                'ordering': ['floor', 'waiter'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('paid', "To'langan"), ('cancelled', 'Bekor qilingan')], default='active', max_length=20, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Boshlangan vaqt')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Yakunlangan vaqt')),
                ('notes', models.TextField(blank=True, verbose_name='Izohlar')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='restaurant.table', verbose_name='Stol')),
                ('waiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='Ofitsant')),
            ],
            options={
                'verbose_name': 'Sessiya',
                'verbose_name_plural': 'Sessiyalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Terminal'), ('click', 'Click'), ('payme', 'Payme'), ('other', 'Boshqa')], default='cash', max_length=20, verbose_name="To'lov turi")),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Summa')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('completed', 'Bajarildi'), ('failed', 'Muvaffaqiyatsiz'), ('refunded', 'Qaytarildi')], default='pending', max_length=20, verbose_name='Holat')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='Tranzaksiya ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="To'langan vaqt")),
                ('notes', models.TextField(blank=True, verbose_name='Izohlar')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to=settings.AUTH_USER_MODEL, verbose_name='Kim qabul qildi')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='restaurant.session', verbose_name='Sessiya')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Miqdori')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('cooking', 'Tayyorlanmoqda'), ('done', 'Tayyor'), ('delivered', 'Yetkazildi'), ('cancelled', 'Bekor qilingan')], default='pending', max_length=20, verbose_name='Holat')),
                ('notes', models.TextField(blank=True, verbose_name='Izohlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Buyurtma berilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='restaurant.menuitem', verbose_name='Taom')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='restaurant.session', verbose_name='Sessiya')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
